### ISSUE TITLE
Is this still worked on?

### ISSUE THREAD

**Issue by andreadev-it** [nvim-neorg/neorg-dirman#8]
Hi @vhyrro ,
I'm working on a rust project related to norg files, is this repository still here for future use? I've also saw some unsafe code and C bindings, which I thought was weird since the functionality it provides doesn't seem to need it, is this setup to do something more complex than it seems?

Thank you and have a nice day

**Comment by vhyrro** [comment]
Yep! There are still things planned for this. Expect some documentation to be released for it soon. I got norgopolis to work within Neovim recently and have been going through all these repos and documenting them :)

**Comment by andreadev-it** [comment]
Ok, thank you for all your hard work on Neorg and its ecosystem :)
